version: "3.7"

services:
  # This service runs the postgres DB used by dagster for run storage, schedule storage,
  # and event log storage. Depending on the hardware you run this Compose on, you may be able
  # to reduce the interval and timeout in the healthcheck to speed up your `docker-compose up` times.
  covid_data_project_postgresql:
    image: postgres:11
    container_name: covid_data_project_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - covid_data_project_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres_user -d postgres_db"]
      interval: 10s
      timeout: 8s
      retries: 5

  covid_data_project_dbt_postgresql:
    image: postgres:16
    container_name: covid_data_project_dbt_postgresql
    environment:
      POSTGRES_USER: ${DBT_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DBT_POSTGRES_PASSWORD}
      POSTGRES_DB: ${DBT_POSTGRES_DB}
    networks:
      - covid_data_project_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBT_POSTGRES_USER} -d ${DBT_POSTGRES_DB}"]
      interval: 10s
      timeout: 8s
      retries: 5
    ports:
      - "5432:5432"

  # This service runs the gRPC server that loads your user code, in both dagster-webserver
  # and dagster-daemon. By setting DAGSTER_CURRENT_IMAGE to its own image, we tell the
  # run launcher to use this same image when launching runs in a new container as well.
  # Multiple containers like this can be deployed separately - each just needs to run on
  # its own port, and have its own entry in the workspace.yaml file that's loaded by the
  # webserver.
  covid_data_project_user_code:
    build:
      context: .
      dockerfile: ./Dockerfile_covid_project
    container_name: covid_data_project_user_code
    expose:
      - "4000"
    ports:
      - "4000:4000"
    image: covid_data_project_user_code_image
    restart: always
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
      DAGSTER_CURRENT_IMAGE: "covid_data_project_user_code_image"
      DBT_POSTGRES_USER: ${DBT_POSTGRES_USER}
      DBT_POSTGRES_PASSWORD: ${DBT_POSTGRES_PASSWORD}
      DBT_POSTGRES_DB: ${DBT_POSTGRES_DB}
      DBT_POSTGRES_HOST: covid_data_project_dbt_postgresql # Connect to the new DBT DB

    networks:
      - covid_data_project_network

  # This service runs dagster-webserver, which loads your user code from the user code container.
  # Since our instance uses the QueuedRunCoordinator, any runs submitted from the webserver will be put on
  # a queue and later dequeued and launched by dagster-daemon.
  covid_data_project_webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: covid_data_project_webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can terminate containers from the webserver
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - covid_data_project_network
    depends_on:
      covid_data_project_postgresql:
        condition: service_healthy
      covid_data_project_user_code:
        condition: service_started

  # This service runs the dagster-daemon process, which is responsible for taking runs
  # off of the queue and launching them, as well as creating runs from schedules or sensors.
  covid_data_project_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: covid_data_project_daemon
    restart: on-failure
    environment:
      DAGSTER_POSTGRES_USER: "postgres_user"
      DAGSTER_POSTGRES_PASSWORD: "postgres_password"
      DAGSTER_POSTGRES_DB: "postgres_db"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - covid_data_project_network
    depends_on:
      covid_data_project_postgresql:
        condition: service_healthy
      covid_data_project_user_code:
        condition: service_started

networks:
  covid_data_project_network:
    driver: bridge
    name: covid_data_project_network